name: NSL Deploy Pipeline - Sandbox Stable
env:
  web_portals: "member_portal, provider_portal, claimsops_portal, nomi_benefits_portal"
  
on:
  merge_group:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      web_portals: 
        description: WEB-portals to Deploy
        required: true
        default: member_portal, provider_portal, claimsops_portal, nomi_benefits_portal, claimsops_portal
jobs:
    test_envs: 
      runs-on: ubuntu-latest
      steps:
      - name: Say member_portal
        run: |
              "${{inputs.web_portals}}" \
              
    deploy_apps:
      uses: "./.github/workflows/test.yml"
      with:
        web_portals: "member_portal, provider_portal, claimsops_portal, nomi_benefits_portal, benefitsadmin_portal"
        
    deploy_test_2:
      uses: "./.github/workflows/test.yml"
      with:
        web_portals: ${{  "teztsxtx"}}
        
    deploy_test_3:
      uses: "./.github/workflows/test.yml"
      with:
        web_portals: ${{"-------------jjjjjjjjjjj"  }}
        
