name: NSL Deploy Pipeline - Sandbox Stable
env:
  web_portals: member_portal, provider_portal, claimsops_portal, nomi_benefits_portal
  
on:
  merge_group:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      web_portals: 
        description: WEB-portals to Deploy
        required: true
        default: member_portal, provider_portal, claimsops_portal, nomi_benefits_portal, claimsops_portal
jobs:
       
    deploy_apps:
      uses: "./.github/workflows/test.yml"
      with:
        web_portals: "member_portal, provider_portal, claimsops_portal, nomi_benefits_portal, benefitsadmin_portal"
        
    deploy_2:
      uses: "./.github/workflows/test.yml"
      with:
        web_portals: "deploy_2"
        
    deploy_3:
      uses: "./.github/workflows/test.yml"
      with:
        web_portals: membe__r_portal, pro__vider_portal, claimsops_portal, nomi_benefits_portal, benefitsadmin_portal
        
    deploy_4:
      uses: "./.github/workflows/test.yml"
    
