name: NSL Deploy Pipeline - Sandbox Stable

on:
  merge_group:
  discussion:
    types: [created, edited, answered]
  workflow_dispatch:
    inputs:
      web_portals: 
        description: WEB-portals to Deploy
        required: true
        default: member_portal, provider_portal, claimsops_portal, nomi_benefits_portal, benefitsadmin_portal
jobs:
    deploy_apps:
      uses: "./.github/workflows/test.yml"
      with:
        web_portals: "${{inputs.web_portals}}"
        
