name: Test

on:
  workflow_call:
    inputs:
      web_portals: 
        description: WEB-portals to Deploy member_portal, provider_portal, claimsops_portal, nomi_benefits_portal, benefitsadmin_portal 
        required: false
        type: string
        default: member_portal, provider_portal, claimsops_portal

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Say member_portal
      if: contains( github.event.inputs.web_portals, 'member_portal')
      run: echo member_portal
    - name: github.event.inputs.web_portals
      if: contains( github.event.inputs.web_portals, 'provider_portal')
      run: echo test1  echo ${{github.event.inputs.web_portals}}  
      
    - name: inputs_web_portals 
      run: echo test2  echo ${{inputs.web_portals}}  

  test_2:
    runs-on: ubuntu-latest
    steps:
    - name: github.event.inputs.web_portals
      run: echo test1  echo ${{github.event.inputs.web_portals}}  
      
    - name: inputs_web_portals 
      run: echo test2  echo ${{inputs.web_portals}}  
          
    - name: Say provider_portal
      run: |
          echo "1234t - ${{github.event.inputs.web_portals}}" \
          echo ${{inputs.web_portals}} 
          
  test_3:
    runs-on: ubuntu-latest
    steps:
    - name: inputs_web_portals 
      run: echo test2  echo ${{inputs.web_portals}}  
          
   
