name: Test

on:
  workflow_dispatch:
    inputs:
      web_portals: 
        description: WEB-portals to Deploy member_portal, provider_portal, claimsops_portal, nomi_benefits_portal, benefitsadmin_portal 
        required: false
        default: member_portal, provider_portal, claimsops_portal

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Say member_portal
      if: contains( github.event.inputs.web_portals, 'member_portal')
      run: echo member_portal
    - name: Say provider_portal
      if: contains( github.event.inputs.web_portals, 'provider_portal')
      run: echo provider_portal 
          | echo ${{github.event.inputs.web_portals}} 
          | echo ${{inputs.web_portals}} 
            
